server:
  port: 9999
#  servlet:
#    context-path: /student
    
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: admin
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgresPlusDialect
    hibernate:
      ddl-auto: create
    show-sql: true
  thymeleaf:
       prefix: classpath:/templates/
       suffix: .html
#  mvc:
#   view:
#      prefix: /WEB-INF/pages
#      suffix: .html
